### ISSUE TITLE
[Feature Request] Automate Crashed Scene Recovery

### ISSUE THREAD

**Issue by shanecolliatie** [unitycoder/UnityLauncher#17]
Using the following technique:
https://support.unity3d.com/hc/en-us/articles/210224803-Can-I-restore-my-unsaved-scene-after-Unity-crash-

Add a checkbox in the settings for enabling the feature, and an edit box to specify the recovery name. Automate the entire procedure when a recovered scene has been detected, so the scene isn't permanently lost when re-launching the project.

**Comment by unitycoder** [comment]
yeah this would be useful, ill check about this later

**Comment by unitycoder** [comment]
this is now included at current version
https://github.com/unitycoder/UnityLauncher/releases/tag/1.012
