### ISSUE TITLE
Request: resizeable window

### ISSUE THREAD

**Issue by geo-at-github** [unitycoder/UnityLauncher#21]
Can you please make the window resizeable.
Resizing the columns might also be a nice feature.

Thanks for this awesome tool.

**Comment by unitycoder** [comment]
yes, would be nice to have.. will see when : )

**Comment by friuns2** [comment]
i have same issue hard to distinguish projects
![image](https://user-images.githubusercontent.com/16543239/35439769-f1c86298-02a4-11e8-8fae-573340a80c75.png)

**Comment by unitycoder** [comment]
latest build now has resizable columns for that list

**Comment by geo-at-github** [comment]
Just created a new pull request which implements persisting column widths in user settings.

**Comment by unitycoder** [comment]
renamed this to columns, and opening separate issue for window
