### ISSUE TITLE
Exception on start

### ISSUE THREAD

**Issue by ice-pro** [unitycoder/UnityLauncher#22]
OS: Windows 10
.NET:
> Microsoft (R) .NET CLR Version Tool  Version 4.6.1055.0
> Copyright (c) Microsoft Corporation.  All rights reserved.
> 
> Versions installed on the machine:
> v2.0.50727
> v4.0.30319

TC: Open program

Error:
```
System.InvalidCastException: Unable to cast object of type 'System.String' to type 'System.Byte[]'.
at UnityLauncher.Form1.UpdateRecentProjectsList()
at UnityLauncher.Form1.Start()
at UnityLauncher.Form1.Form1_Load(Object sender, EventArgs e)
```

**Comment by unitycoder** [comment]
hmm looks like it happens on this line then, not yet sure why:
https://github.com/unitycoder/UnityLauncher/blob/master/UnityLauncher/Form1.cs#L264

**Comment by ice-pro** [comment]
why are you doing that conversion magic? afaik `key.GetValue` should give you a string.

**Comment by unitycoder** [comment]
they did it here also, saying that it returns object, actually cant remember if tested without it.. (and it works on most computers apparently)
https://msdn.microsoft.com/en-us/library/fdf576x1(v=vs.110).aspx

looks like should check if the data is binary or not, i can add that later:
https://stackoverflow.com/a/14668394/5452781

**Comment by unitycoder** [comment]
can you try this build 
https://www.dropbox.com/s/d3lnprpvh1zyjnt/UnityLauncher-bytefix.zip?dl=0

**Comment by ice-pro** [comment]
This version works fine!
But on the first tab the project name contains all the path to it, starting from C:\Program Files\...

**Comment by unitycoder** [comment]
ok, i was using forward slash to split, LastIndexOf("/"),
so ill switch to this or check both 
https://msdn.microsoft.com/en-us/library/system.io.path.directoryseparatorchar(v=vs.110).aspx

**Comment by unitycoder** [comment]
can you try this build,
https://www.dropbox.com/s/nfgfs6vff6p1igu/UnityLauncher-pathfix.zip?dl=0

**Comment by ice-pro** [comment]
Cool, I am very happy now. Can you release fixed version?

**Comment by unitycoder** [comment]
its now live
https://github.com/unitycoder/UnityLauncher/releases (1.013)

**Comment by ice-pro** [comment]
Thank you!
