### ISSUE TITLE
git branch name collumn

### ISSUE THREAD

**Issue by friuns2** [unitycoder/UnityLauncher#26]
if you have several folders with same project but different branches

**Comment by unitycoder** [comment]
how to check that?

i guess if project has ".git" folder, we can read some file inside that?
or do we need to query with some git command?

**Comment by friuns2** [comment]
git branch is the command, and in git folder its seems to be .git\HEAD

https://i.imgur.com/jyMlzNv.png

**Comment by unitycoder** [comment]
now available in latest build, reads .git/HEAD file
https://github.com/unitycoder/UnityLauncher/releases
