### ISSUE TITLE
Automatically select closest suitable version

### ISSUE THREAD

**Issue by unitycoder** [unitycoder/UnityLauncher#3]
Currently only exact version works (5.6.1f1 project cannot be automatically opened with 5.6.2f1 or patch releases)

Should add option to upgrade project into next compatible version, for example:
5.6.1f1 project would open in 5.6.1p1 etc.

**Comment by softfruit** [comment]
Had a stab at this,

basic idea:

- strip the letters
- make a list of all available versions
- add the version we want to open
-   order the list
- find index of our version in the list
- its neighbours (index-1 , index+1) are the next up and next down

(the one caveat is 2017 throws the sequential order out of whack, so i have a second function to split and test 2017s with each other, and the rest with the rest)

https://pastebin.com/uK8uF4gJ

**Comment by unitycoder** [comment]
thanks! to keep it simple, ill probably just give user your sorted list, and they can pick the version..and see if that works good enough.
