### ISSUE TITLE
unity 4 versions not detected

### ISSUE THREAD

**Issue by friuns2** [unitycoder/UnityLauncher#32]
unity 4 versions not detected: https://i.imgur.com/qexOfBj.png

also why its called mining edition? i hope its not running bitcoin mining in background :D

also i checked unitys new official launcher but its horrible, there no search, half projects not visible, and a lot features missing. so keep it up this project!

**Comment by unitycoder** [comment]
Probably not too difficult to fix/add, but how long you are still planning to use Unity4..?

- looks like project version data in 4.x is inside "ProjectSettings.asset" binary file
- need to add registry scanning for 4.x also https://github.com/unitycoder/UnityLauncher/issues/6

hmm...background-miner..HMMM!! *nope, just picking some random words before publish : D

**Comment by friuns2** [comment]
i have a lot old projects in unity 4 where i look how i done things or copying assets from there. so yeah very long :P

**Comment by unitycoder** [comment]
looks like it works with just small modifications.. ill upload the build later

**Comment by unitycoder** [comment]
can try the latest release,
https://github.com/unitycoder/UnityLauncher/releases

**Comment by friuns2** [comment]
works with some bugs: https://i.imgur.com/gbEvTG1.png
1. its always showing unity 4 projects 2 times 
2. what ag:unit means? :) should be 4.7.2

**Comment by unitycoder** [comment]
could be the projectsettings assets contains unknown extra data..
for me it shows name at this location:
![image](https://user-images.githubusercontent.com/5438317/35778018-0c10f70a-09f3-11e8-8da5-a49421d9ec0e.png)

can you send me few projectsettings.assets from different 4.x projects?
or tale screenshots with this,
https://hexed.it/

project listed twice, didnt happen here.. if you can check with regedit, if those projects really are listed on both registry folders?

from these locations:
"current user\SOFTWARE\Unity Technologies\Unity Editor 5.x"
"current user\SOFTWARE\Unity Technologies\Unity Editor 4.x
then scroll down for those recent-project items.

**Comment by friuns2** [comment]
project file is text file because i set from binary to text in editor settings

%YAML 1.1
%TAG !u! tag:unity3d.com,2011:
--- !u!129 &1
PlayerSettings:
  m_ObjectHideFlags: 0
  serializedVersion: 3
  AndroidProfiler: 0
  defaultScreenOrientation: 3
  targetDevice: 2
  targetGlesGraphics: 1
  targetIOSGraphics: -1
  targetResolution: 0
  accelerometerFrequency: 60
  companyName: Soulkey/Phaneron
  productName: TrackRacing Pursuit
  defaultCursor: {fileID: 0}

**Comment by friuns2** [comment]
in 5.x its binary type hard to read, 4.x don't see any duplicates

i think i by mistake tried open unity 4 project in unity 5 and then canceled
i have same project in both unitys
https://i.imgur.com/jTJmKEO.png

**Comment by unitycoder** [comment]
latest build tries to check version info from Library folder files also.

but i think best solution for 4.x projects is to put that "ProjectVersion.txt" there manually,
since its not likely that users would update their 4.x projects to another 4.x versions too often..
