### ISSUE TITLE
Open a Unity folder directly from UnityLauncher

### ISSUE THREAD

**Issue by bourgeoismaxime** [unitycoder/UnityLauncher#40]
Hello,
Would it be possible to add a button in UnityLauncher to open a Unity project we never opened before ? I have placed old projects back in my HDD and i always have to find the correct Unity version before I can open them with UnityLauncher.

**Comment by unitycoder** [comment]
yeah, should be easy to add.

i'm thinking:
- [+] add project button
- displays file or folder dialog to browse for it
- launches that project

also,
if you are already in the project folder with explorer, you can open the project with context menu:
https://github.com/unitycoder/UnityLauncher/wiki/Adding-Explorer-Context-Menu

**Comment by bourgeoismaxime** [comment]
Sadly I tried the Explorer Context Menu at my work but it does not work for me (I guess permissions related or something like that). I guessed that if the context menu can do it then it should not be that hard to add in the UI.

**Comment by unitycoder** [comment]
this is now live (or at least the first version of it),
https://github.com/unitycoder/UnityLauncher/releases

see comments, https://github.com/unitycoder/UnityLauncher/issues/47#issuecomment-377182421
