### ISSUE TITLE
Unhandled exception when resizing a column in Projects

### ISSUE THREAD

**Issue by Raebyn** [unitycoder/UnityLauncher#41]
At first, thank you very much for this useful tool!

One reproducible bug I found is an error message I get - every time I resize a column in the Projects tab.
I already commented this at the commit, but since I'm not sure if that's the right place, I'm adding it here as an issue, too:

"System.ArgumentNullException: Der Wert darf nicht NULL sein.
Parametername: collection
   bei System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   bei UnityLauncher.Form1.gridRecent_ColumnWidthChanged(Object sender, DataGridViewColumnEventArgs e)
   bei System.Windows.Forms.DataGridView.OnColumnWidthChanged(DataGridViewColumnEventArgs e)
   bei System.Windows.Forms.DataGridView.OnBandThicknessChanged(DataGridViewBand dataGridViewBand)
   bei System.Windows.Forms.DataGridViewBand.set_ThicknessInternal(Int32 value)
   bei System.Windows.Forms.DataGridViewBand.set_Thickness(Int32 value)
   bei System.Windows.Forms.DataGridView.EndColumnResize(MouseEventArgs e)
   bei System.Windows.Forms.DataGridView.OnMouseUp(MouseEventArgs e)
   bei System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   bei System.Windows.Forms.Control.WndProc(Message& m)
   bei System.Windows.Forms.DataGridView.WndProc(Message& m)
   bei System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   bei System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   bei System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

Hope this helps. I'm using the "4 Months To Go" Edition 20, whatever this means.

**Comment by unitycoder** [comment]
can you try this build,
https://www.dropbox.com/s/0byo6z9ytfs98ct/UnityLauncher21-beta.zip?dl=0
(it has some default values added to the widths so shouldnt be null)

**Comment by geo-at-github** [comment]
The gridColumnWidths xml in AppConfig.xml was indeed missing and caused the error for me as well (pulled 5 minutes ago).
I have created a patch and pull request to fix it.
https://github.com/unitycoder/UnityLauncher/pull/42

**Comment by geo-at-github** [comment]
Hi, your 21beta build works. I have also added a patch to the pull request  (reverted the old one and added a new one). Default values are no longer needed.

Btw.: To propery reproduce this error you had to delete the data in "%AppData%\..\Local\UnityCoder.com". I guess that's why it worked for you. Once you have saved the data it will just work every time. Maybe we should always delete the data in "%AppData%\..\Local\UnityCoder.com" to make sure tests are done against a "clean install" environment. Maybe VisualStudio can do the automatically?

**Comment by unitycoder** [comment]
@Raebyn can test the latest build if it works for you
https://github.com/unitycoder/UnityLauncher/releases

@geo-at-github ok thanks! yeah would be nice to test with clean settings inside vs, didnt find anything useful related to that yet..

**Comment by Raebyn** [comment]
@unitycoder 
Sorry for answering so late - thank you very much, the latest build works for me!
