### ISSUE TITLE
Re-Scan Button for new Unity Projects (Feature Request)

### ISSUE THREAD

**Issue by Raebyn** [unitycoder/UnityLauncher#47]
Maybe I've overlooked something - but what I'm missing is something like a "re-scan for new projects" button. Currently, when I checkout a new project via svn (or the project is moved to another folder), that project isn't recognized automatically by the launcher. This is especially problematic if the projects needs a new Unity version I haven't installed yet (and don't know yet).

Would be great if you had the time to add something like that. Or give me a hint if the launcher can already do that? I've seen the refresh button for the Unity versions - something like that for the projects would be nice. :) (there should be room enough beside the huge search input)

edit: Ok, so there is a Refresh with F5. But it's not consistent as stated above, since you can refresh the Unity installations list both by F5 or that button. I only found out about the implemented F5 function by stumbling over the project overview here.

**Comment by unitycoder** [comment]
This feature is coming in next update, can browse/add new project to the list
(and its already in the code, just havent made build yet, also refresh button is added on project list page.. f5 is bit hidden feature)
https://github.com/unitycoder/UnityLauncher/issues/40

For new projects or download projects, i usually use the explorer context menu, it opens version selector if there is no version info in the project, or if you are missing the unity version.

**Comment by Raebyn** [comment]
Ah, that's cool. Hadn't thought about the context menu option (don't use this yet), but for now I'll wait for the next update then. Nice!

**Comment by unitycoder** [comment]
this is now live, https://github.com/unitycoder/UnityLauncher/releases

*although the default Browse for a folder dialog in Windows is super annoying.. supposedly only option to have better browse folder window is to use some external libraries, https://www.mking.net/blog/a-better-alternative-to-the-winforms-folderbrowserdialog-using-ookii-dialogs (but that would add extra file and/or extra file size.. maybe consider it later)
