### ISSUE TITLE
Some typing errors in strings (Form1.cs)

### ISSUE THREAD

**Issue by Raebyn** [unitycoder/UnityLauncher#48]
I've found some typing errors in strings in Form1.cs

I'm not so familiar with github yet, but I started a pull request and hope this works. :)

**Comment by unitycoder** [comment]
for some reason it shows the whole file as changed (every line).. so i'm not sure what was changed.. 

looks like this issue,
https://stackoverflow.com/questions/19593909/git-diff-sees-whole-file-as-changed-when-its-not

are you using commandline git, or sourcetree, github desktop?

**Comment by Raebyn** [comment]
Oh, I see ... my fault, I just uploaded the single file manually via browser. I guess that (maybe) only works for new files. I closed the pull request and I will see if it helps to use one of the tools you mentioned.

**Comment by Raebyn** [comment]
Looks like the second try worked. What I haven't found in the files were e.g. the names of the tabs. 
Maybe you'd like to change "Unity's" to "Unitys" or "Unity Versions" 
and in Settings: "Explorer context menu:  Install / Uninstall" (consistency)
and "Check for Updates" ?

Yeah ... nitpicking by a non-coder.  :)

**Comment by unitycoder** [comment]
ok, looks fine now thanks! (ill merge it sometime this week)

**Comment by unitycoder** [comment]
this is now live, https://github.com/unitycoder/UnityLauncher/releases
