### ISSUE TITLE
Multiple install roots

### ISSUE THREAD

**Issue by AndrewRH** [unitycoder/UnityLauncher#5]
Hi, great tool.  IT would be nice to be able to specify multiple roots.  For example I have some Unity installs in Program Files and some in Program Files x86, and also I have on Program Files in other drives (due to running out of space).
Thanks,

**Comment by unitycoder** [comment]
thought of this also, should be possible to add.. maybe ill make it as an listbox of root folders.

**Comment by unitycoder** [comment]
can you try this build, https://github.com/unitycoder/UnityLauncher/releases/tag/1.0.31

there is listbox for root folders

**Comment by unitycoder** [comment]
fixed multiple path settings saving/loading in this one
https://github.com/unitycoder/UnityLauncher/releases/tag/1.0.5
