### ISSUE TITLE
Support for scanning Unity 4.x and 2017.x registry

### ISSUE THREAD

**Issue by AndrewRH** [unitycoder/UnityLauncher#6]
I noticed it's only scanning the Unity 5.x registry folder so it would be nice to scan for these other ones too.

**Comment by unitycoder** [comment]
if you have the registry paths for those then let me know (i think never had 4.x installed on this machine..)

**Comment by ice-pro** [comment]
+ version 2018

**Comment by unitycoder** [comment]
it shows 2017, 2018 projects for me..
by scanning from "current user\SOFTWARE\Unity Technologies\Unity Editor 5.x"
at, https://github.com/unitycoder/UnityLauncher/blob/master/UnityLauncher/Form1.cs#L249

which registry paths you have for other versions?

**Comment by unitycoder** [comment]
ok, scanning for 4.x projects works now (available in next build)

**Comment by unitycoder** [comment]
closing this since 2017, 2018 projects seem to be listed in the 5.x registry.. or is that just because i had 5.x installed before 2017/18 (?)
