### ISSUE TITLE
Explorer Context menu not working, Cannot find registry key: Software\classes\dictionary\background\shell

### ISSUE THREAD

**Issue by friuns2** [unitycoder/UnityLauncher#65]
![image](https://user-images.githubusercontent.com/16543239/41034232-a5fdf3ba-6991-11e8-96f8-26b1f57f4431.png)

**Comment by friuns2** [comment]
yes i dont have but i have only Software\classes\dictionary\shell

**Comment by friuns2** [comment]
if i create manually directory Software\classes\dictionary\background\shell
then Install works, so i guess you have to create it if its not there

**Comment by unitycoder** [comment]
ok thanks!
ill add some check there later (and create the folder if it doesnt exists)

**Comment by unitycoder** [comment]
just noticed the install button doesn't work on one different pc either.. so need to look into that

**Comment by friuns2** [comment]
on my work pc with windows 10 not working but on home pc with win 10 it works...
