### ISSUE TITLE
Download Version not working

### ISSUE THREAD

**Issue by softfruit** [unitycoder/UnityLauncher#8]
Your web scraping didn't work for me on v5.6.0f3 
instead of manual replaces on the html, try a regular expression:

https://pastebin.com/WKVMzE91

**Comment by unitycoder** [comment]
thanks, will add to next update.

how would make that pick only the download assistant exe? (currently it picks full installer also, but that takes too long to load..)

was testing here, but fails on that meta tag list:
https://regex101.com/r/nv5p2J/2

**Comment by softfruit** [comment]
Just remove all the whitespace

https://regex101.com/r/cjiJ8K/1

**Comment by unitycoder** [comment]
thanks! its now included in the latest version
